# vm-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-metrics
  namespace: tensuns
spec:
  selector:
    matchLabels:
      app: victoria-metrics
  template:
    metadata:
      labels:
        app: victoria-metrics
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: victoria-metrics-data
      containers:
        - name: vm
          #image: victoriametrics/victoria-metrics:v1.121.0
          image: *-registry-vpc.cn-shanghai.cr.aliyuncs.com/tools/victoriametrics/victoria-metrics:v1.121.0
          imagePullPolicy: IfNotPresent
          args:
            - -storageDataPath=/var/lib/victoria-metrics-data
            - -retentionPeriod=1d
          ports:
            - containerPort: 8428
              name: http
          volumeMounts:
            - mountPath: /var/lib/victoria-metrics-data
              name: storage
---
apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics
  namespace: tensuns
spec:
  #type: NodePort
  type: ClusterIP
  ports:
    - port: 8428
  selector:
    app: victoria-metrics



---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: victoria-metrics-data
  namespace: tensuns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: alicloud-disk-essd
  resources:
    requests:
      storage: 20Gi





#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: victoria-metrics-data
#spec:
#  accessModes:
#    - ReadWriteOnce
#  capacity:
#    storage: 20Gi
#  storageClassName: local-storage
#  local:
#    path: /data/k8s/vm
#  persistentVolumeReclaimPolicy: Retain
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: kubernetes.io/hostname
#              operator: In
#              values:
#                - node2
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: victoria-metrics-data
#  namespace: tensuns
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 20Gi
#  storageClassName: local-storage
#
