apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom
  namespace: tensuns
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: alicloud-disk-essd
