apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo3-guestbook-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo3-guestbook-ui
  template:
    metadata:
      labels:
        app: demo3-guestbook-ui
    spec:
      containers:
      - image: nginx:1.17.7
        name: demo3-guestbook-ui
        ports:
        - containerPort: 80
