apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: ops-monit
  name: vector
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vector
  labels:
    app.kubernetes.io/name: vector
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - nodes
      - pods
    verbs:
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vector
  labels:
    app.kubernetes.io/name: vector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vector
subjects:
  - kind: ServiceAccount
    name: vector
    namespace: ops-monit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector
  namespace: ops-monit
  labels:
    app.kubernetes.io/name: vector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vector
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/name: vector
        vector.dev/exclude: "true"
    spec:
      serviceAccountName: vector
      dnsPolicy: ClusterFirst
      containers:
        - name: vector
          image: "registry.cn-shenzhen.aliyuncs.com/starsl/vector:0.42.0-alpine"
          imagePullPolicy: IfNotPresent
          args:
            - --config-dir
            - /etc/vector/
          env:
            - name: TZ
              value: Asia/Shanghai
          ports:
            - name: api
              containerPort: 8686
              protocol: TCP
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 100Mi
          volumeMounts:
            - name: data
              mountPath: "/vector-data-dir"
            - name: config
              mountPath: "/etc/vector/"
              readOnly: true
      terminationGracePeriodSeconds: 60
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: vector
              topologyKey: kubernetes.io/hostname
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          projected:
            sources:
              - configMap:
                  name: vector
---
apiVersion: v1
kind: Service
metadata:
  namespace: ops-monit
  name: vector
  labels:
    app.kubernetes.io/name: vector
spec:
  ports:
    - name: api
      port: 8686
      protocol: TCP
  selector:
    app.kubernetes.io/name: vector
  type: NodePort