# [{'api_version': None,
#  'kind': None,
#  'metadata': {'annotations': None,
#               'creation_timestamp': datetime.datetime(2024, 6, 6, 9, 27, 15, tzinfo=tzutc()),
#               'deletion_grace_period_seconds': None,
#               'deletion_timestamp': None,
#               'finalizers': None,
#               'generate_name': 'my-nginx-648f54d678-',
#               'generation': None,
#               'labels': {'app': 'my-nginx', 'pod-template-hash': '648f54d678'},
#               'managed_fields': [{'api_version': 'v1',
#                                   'fields_type': 'FieldsV1',
#                                   'fields_v1': {'f:metadata': {'f:generateName': {},
#                                                                'f:labels': {'.': {},
#                                                                             'f:app': {},
#                                                                             'f:pod-template-hash': {}},
#                                                                'f:ownerReferences': {'.': {},
#                                                                                      'k:{"uid":"058c2f2c-08d8-43e4-a33d-8cb93e4bbb22"}': {}}},
#                                                 'f:spec': {'f:containers': {'k:{"name":"my-nginx"}': {'.': {},
#                                                                                                       'f:image': {},
#                                                                                                       'f:imagePullPolicy': {},
#                                                                                                       'f:name': {},
#                                                                                                       'f:ports': {'.': {},
#                                                                                                                   'k:{"containerPort":80,"protocol":"TCP"}': {'.': {},
#                                                                                                                                                               'f:containerPort': {},
#                                                                                                                                                               'f:protocol': {}}},
#                                                                                                       'f:resources': {},
#                                                                                                       'f:terminationMessagePath': {},
#                                                                                                       'f:terminationMessagePolicy': {}}},
#                                                            'f:dnsPolicy': {},
#                                                            'f:enableServiceLinks': {},
#                                                            'f:restartPolicy': {},
#                                                            'f:schedulerName': {},
#                                                            'f:securityContext': {},
#                                                            'f:terminationGracePeriodSeconds': {}}},
#                                   'manager': 'kube-controller-manager',
#                                   'operation': 'Update',
#                                   'subresource': None,
#                                   'time': datetime.datetime(2024, 6, 6, 9, 27, 15, tzinfo=tzutc())},
#                                  {'api_version': 'v1',
#                                   'fields_type': 'FieldsV1',
#                                   'fields_v1': {'f:status': {'f:conditions': {'k:{"type":"ContainersReady"}': {'.': {},
#                                                                                                                'f:lastProbeTime': {},
#                                                                                                                'f:lastTransitionTime': {},
#                                                                                                                'f:status': {},
#                                                                                                                'f:type': {}},
#                                                                               'k:{"type":"Initialized"}': {'.': {},
#                                                                                                            'f:lastProbeTime': {},
#                                                                                                            'f:lastTransitionTime': {},
#                                                                                                            'f:status': {},
#                                                                                                            'f:type': {}},
#                                                                               'k:{"type":"PodReadyToStartContainers"}': {'.': {},
#                                                                                                                          'f:lastProbeTime': {},
#                                                                                                                          'f:lastTransitionTime': {},
#                                                                                                                          'f:status': {},
#                                                                                                                          'f:type': {}},
#                                                                               'k:{"type":"Ready"}': {'.': {},
#                                                                                                      'f:lastProbeTime': {},
#                                                                                                      'f:lastTransitionTime': {},
#                                                                                                      'f:status': {},
#                                                                                                      'f:type': {}}},
#                                                              'f:containerStatuses': {},
#                                                              'f:hostIP': {},
#                                                              'f:hostIPs': {},
#                                                              'f:phase': {},
#                                                              'f:podIP': {},
#                                                              'f:podIPs': {'.': {},
#                                                                           'k:{"ip":"10.1.1.189"}': {'.': {},
#                                                                                                     'f:ip': {}}},
#                                                              'f:startTime': {}}},
#                                   'manager': 'kubelet',
#                                   'operation': 'Update',
#                                   'subresource': 'status',
#                                   'time': datetime.datetime(2024, 6, 6, 9, 27, 18, tzinfo=tzutc())}],
#               'name': 'my-nginx-648f54d678-rgjh4',
#               'namespace': 'demo',
#               'owner_references': [{'api_version': 'apps/v1',
#                                     'block_owner_deletion': True,
#                                     'controller': True,
#                                     'kind': 'ReplicaSet',
#                                     'name': 'my-nginx-648f54d678',
#                                     'uid': '058c2f2c-08d8-43e4-a33d-8cb93e4bbb22'}],
#               'resource_version': '2888493',
#               'self_link': None,
#               'uid': '8c172bc9-0113-4055-b729-d822dc561827'},
#  'spec': {'active_deadline_seconds': None,
#           'affinity': None,
#           'automount_service_account_token': None,
#           'containers': [{'args': None,
#                           'command': None,
#                           'env': None,
#                           'env_from': None,
#                           'image': 'nginx',
#                           'image_pull_policy': 'Always',
#                           'lifecycle': None,
#                           'liveness_probe': None,
#                           'name': 'my-nginx',
#                           'ports': [{'container_port': 80,
#                                      'host_ip': None,
#                                      'host_port': None,
#                                      'name': None,
#                                      'protocol': 'TCP'}],
#                           'readiness_probe': None,
#                           'resize_policy': None,
#                           'resources': {'claims': None,
#                                         'limits': None,
#                                         'requests': None},
#                           'restart_policy': None,
#                           'security_context': None,
#                           'startup_probe': None,
#                           'stdin': None,
#                           'stdin_once': None,
#                           'termination_message_path': '/dev/termination-log',
#                           'termination_message_policy': 'File',
#                           'tty': None,
#                           'volume_devices': None,
#                           'volume_mounts': [{'mount_path': '/var/run/secrets/kubernetes.io/serviceaccount',
#                                              'mount_propagation': None,
#                                              'name': 'kube-api-access-8d2rz',
#                                              'read_only': True,
#                                              'sub_path': None,
#                                              'sub_path_expr': None}],
#                           'working_dir': None}],
#           'dns_config': None,
#           'dns_policy': 'ClusterFirst',
#           'enable_service_links': True,
#           'ephemeral_containers': None,
#           'host_aliases': None,
#           'host_ipc': None,
#           'host_network': None,
#           'host_pid': None,
#           'host_users': None,
#           'hostname': None,
#           'image_pull_secrets': None,
#           'init_containers': None,
#           'node_name': 'docker-desktop',
#           'node_selector': None,
#           'os': None,
#           'overhead': None,
#           'preemption_policy': 'PreemptLowerPriority',
#           'priority': 0,
#           'priority_class_name': None,
#           'readiness_gates': None,
#           'resource_claims': None,
#           'restart_policy': 'Always',
#           'runtime_class_name': None,
#           'scheduler_name': 'default-scheduler',
#           'scheduling_gates': None,
#           'security_context': {'fs_group': None,
#                                'fs_group_change_policy': None,
#                                'run_as_group': None,
#                                'run_as_non_root': None,
#                                'run_as_user': None,
#                                'se_linux_options': None,
#                                'seccomp_profile': None,
#                                'supplemental_groups': None,
#                                'sysctls': None,
#                                'windows_options': None},
#           'service_account': 'default',
#           'service_account_name': 'default',
#           'set_hostname_as_fqdn': None,
#           'share_process_namespace': None,
#           'subdomain': None,
#           'termination_grace_period_seconds': 30,
#           'tolerations': [{'effect': 'NoExecute',
#                            'key': 'node.kubernetes.io/not-ready',
#                            'operator': 'Exists',
#                            'toleration_seconds': 300,
#                            'value': None},
#                           {'effect': 'NoExecute',
#                            'key': 'node.kubernetes.io/unreachable',
#                            'operator': 'Exists',
#                            'toleration_seconds': 300,
#                            'value': None}],
#           'topology_spread_constraints': None,
#           'volumes': [{'aws_elastic_block_store': None,
#                        'azure_disk': None,
#                        'azure_file': None,
#                        'cephfs': None,
#                        'cinder': None,
#                        'config_map': None,
#                        'csi': None,
#                        'downward_api': None,
#                        'empty_dir': None,
#                        'ephemeral': None,
#                        'fc': None,
#                        'flex_volume': None,
#                        'flocker': None,
#                        'gce_persistent_disk': None,
#                        'git_repo': None,
#                        'glusterfs': None,
#                        'host_path': None,
#                        'iscsi': None,
#                        'name': 'kube-api-access-8d2rz',
#                        'nfs': None,
#                        'persistent_volume_claim': None,
#                        'photon_persistent_disk': None,
#                        'portworx_volume': None,
#                        'projected': {'default_mode': 420,
#                                      'sources': [{'cluster_trust_bundle': None,
#                                                   'config_map': None,
#                                                   'downward_api': None,
#                                                   'secret': None,
#                                                   'service_account_token': {'audience': None,
#                                                                             'expiration_seconds': 3607,
#                                                                             'path': 'token'}},
#                                                  {'cluster_trust_bundle': None,
#                                                   'config_map': {'items': [{'key': 'ca.crt',
#                                                                             'mode': None,
#                                                                             'path': 'ca.crt'}],
#                                                                  'name': 'kube-root-ca.crt',
#                                                                  'optional': None},
#                                                   'downward_api': None,
#                                                   'secret': None,
#                                                   'service_account_token': None},
#                                                  {'cluster_trust_bundle': None,
#                                                   'config_map': None,
#                                                   'downward_api': {'items': [{'field_ref': {'api_version': 'v1',
#                                                                                             'field_path': 'metadata.namespace'},
#                                                                               'mode': None,
#                                                                               'path': 'namespace',
#                                                                               'resource_field_ref': None}]},
#                                                   'secret': None,
#                                                   'service_account_token': None}]},
#                        'quobyte': None,
#                        'rbd': None,
#                        'scale_io': None,
#                        'secret': None,
#                        'storageos': None,
#                        'vsphere_volume': None}]},
#  'status': {'conditions': [{'last_probe_time': None,
#                             'last_transition_time': datetime.datetime(2024, 6, 6, 9, 27, 18, tzinfo=tzutc()),
#                             'message': None,
#                             'reason': None,
#                             'status': 'True',
#                             'type': 'PodReadyToStartContainers'},
#                            {'last_probe_time': None,
#                             'last_transition_time': datetime.datetime(2024, 6, 6, 9, 27, 15, tzinfo=tzutc()),
#                             'message': None,
#                             'reason': None,
#                             'status': 'True',
#                             'type': 'Initialized'},
#                            {'last_probe_time': None,
#                             'last_transition_time': datetime.datetime(2024, 6, 6, 9, 27, 18, tzinfo=tzutc()),
#                             'message': None,
#                             'reason': None,
#                             'status': 'True',
#                             'type': 'Ready'},
#                            {'last_probe_time': None,
#                             'last_transition_time': datetime.datetime(2024, 6, 6, 9, 27, 18, tzinfo=tzutc()),
#                             'message': None,
#                             'reason': None,
#                             'status': 'True',
#                             'type': 'ContainersReady'},
#                            {'last_probe_time': None,
#                             'last_transition_time': datetime.datetime(2024, 6, 6, 9, 27, 15, tzinfo=tzutc()),
#                             'message': None,
#                             'reason': None,
#                             'status': 'True',
#                             'type': 'PodScheduled'}],
#             'container_statuses': [{'allocated_resources': None,
#                                     'container_id': 'docker://bde8e02dae8fcdcffb91c58ca601d0de4ccdf0edff54fbb6435189f4ec617bd4',
#                                     'image': 'nginx:latest',
#                                     'image_id': 'docker-pullable://nginx@sha256:0f04e4f646a3f14bf31d8bc8d885b6c951fdcf42589d06845f64d18aec6a3c4d',
#                                     'last_state': {'running': None,
#                                                    'terminated': None,
#                                                    'waiting': None},
#                                     'name': 'my-nginx',
#                                     'ready': True,
#                                     'resources': None,
#                                     'restart_count': 0,
#                                     'started': True,
#                                     'state': {'running': {'started_at': datetime.datetime(2024, 6, 6, 9, 27, 18, tzinfo=tzutc())},
#                                               'terminated': None,
#                                               'waiting': None}}],
#             'ephemeral_container_statuses': None,
#             'host_i_ps': [{'ip': '192.168.65.3'}],
#             'host_ip': '192.168.65.3',
#             'init_container_statuses': None,
#             'message': None,
#             'nominated_node_name': None,
#             'phase': 'Running',
#             'pod_i_ps': [{'ip': '10.1.1.189'}],
#             'pod_ip': '10.1.1.189',
#             'qos_class': 'BestEffort',
#             'reason': None,
#             'resize': None,
#             'resource_claim_statuses': None,
#             'start_time': datetime.datetime(2024, 6, 6, 9, 27, 15, tzinfo=tzutc())}}]



import datetime
data = {
    'api_version': 'v1',
    'items': [{
        'api_version': None,
        'kind': None,
        'metadata': {
            'annotations': None,
            'creation_timestamp': datetime.datetime(2024, 6, 6, 9, 27, 15),
            'deletion_grace_period_seconds': None,
            'finalizers': None,
            'generate_name': 'my-nginx-648f54d678-',
            'generation': None,
            'labels': {'app': 'my-nginx', 'pod-template-hash': '648f54d678'},
            'name': 'my-nginx-648f54d678-rgjh4',
            'namespace': 'demo',
            'owner_references': None,
            'resource_version': '999999',
            'self_link': '/api/v1/namespaces/demo/pods/my-nginx-648f54d678-rgjh4',
            'uid': '8c172bc9-0113-4055-b729-d822dc561827'
        },
        'spec': {},
        'status': {
            'conditions': [],
            'container_statuses': [],
            'host_ip': '',
            'init_container_statuses': [],
            'message': '',
            'nominated_node_name': '',
            'phase': '',
            'pod_ip': '',
            'qos_class': '',
            'reason': '',
            'start_time': None
        }
    }],
}


for pod in data["items"]:
    print(pod["metadata"]["namespace"])