---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: alertmanager-disk-pvc
  namespace: tensuns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: alicloud-disk-essd
  resources:
    requests:
      storage: 20Gi


---
#简单使用阿里云的ack集群的云硬盘存储，在控制台创建pv pvc