apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-cluster-a
  namespace: argocd
spec:
  destination:
    namespace: directory-guestbook
    server: https://172.21.0.6:6443
  project: myproject
  source:
    path: guestbook
    repoURL: https://jihulab.com/devops_course/argocd-example-apps.git
    targetRevision: master
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true