- job_name: multi_mysqld_exporter
  scrape_interval: 15s
  scrape_timeout: 5s
  metrics_path: /probe
  consul_sd_configs:
      ## consul 服务地址
    - server: 'consel:8500'
      token: 'fe48c9a4-364e-af23-81df-9f28303012af'
      refresh_interval: 30s
      services: ['selfrds_exporter']
  relabel_configs:
    - source_labels: [__meta_consul_tags]
      regex: .*OFF.*
      action: drop
    - source_labels: [__meta_consul_service_address,__meta_consul_service_port]
      regex: ([^:]+)(?::\d+)?;(\d+)
      target_label: __param_target
      replacement: $1:$2
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      ## mysql exporter 服务地址和端口
      replacement: mysql-exporter.kubesphere-monitoring-system.svc:9104  #mysqld-exporter的端口
    - source_labels: ['__meta_consul_service_metadata_vendor']
      target_label: vendor
    - source_labels: ['__meta_consul_service_metadata_region']
      target_label: region
    - source_labels: ['__meta_consul_service_metadata_group']
      target_label: group
    - source_labels: ['__meta_consul_service_metadata_account']
      target_label: account
    - source_labels: ['__meta_consul_service_metadata_name']
      target_label: name
    - source_labels: ['__meta_consul_service_metadata_iid']
      target_label: iid
    - source_labels: ['__meta_consul_service_metadata_exp']
      target_label: exp
    - source_labels: ['__meta_consul_service_metadata_cpu']
      target_label: cpu
    - source_labels: ['__meta_consul_service_metadata_mem']
      target_label: mem
    - source_labels: ['__meta_consul_service_metadata_disk']
      target_label: disk
    - source_labels: ['__meta_consul_service_metadata_itype']
      target_label: itype
