{
 "title": "NGINX请求日志分析看板【日归档数据】 20250616 StarsL.cn",
 "description": "基于ClickHouse已入库的NGINX请求日志数据，按日维度进行聚合归档，生成每日请求数据的分析看板",
 "tags": [
  "nginx",
  "ClickHouse",
  "StarsL.cn"
 ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "db", "label": "db", "query": "nginxlogs" },
   { "name": "project", "label": "项目", "query": "show tables from $db" },
   {
    "name": "domain",
    "label": "域名",
    "query": "select\n`域名`,sum(`总PV`) as pv\nFROM ${db}.${project}\n\tPREWHERE $__timeFilter(`日期`) \n\tgroup by `域名`\n        order by pv desc"
   }
  ]
 },
 "panels": [
  {
   "title": "每日高峰时段数据分析(每0.5小时为1个周期，取PV最大的周期的时段)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "高峰时段QPS曲线图",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT `日期` as time, `最大QPS`,`P99QPS` from ${db}.${project} prewhere $__timeFilter(`日期`) and `域名` = '${domain}'\r\norder by time"
    }
   ]
  },
  {
   "title": "高峰时段响应时间曲线图",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT `日期` as time, `平均RT`,`P99RT`,`P90RT` from ${db}.${project} prewhere $__timeFilter(`日期`) and `域名` = '${domain}'\r\norder by time"
    }
   ]
  },
  {
   "title": "高峰时段各阶段响应时间分布占比",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT `日期` as time, `100ms以下`,`100-500ms`,`500-1kms`,`1k-2kms`,`2kms以上` from ${db}.${project} prewhere $__timeFilter(`日期`) and `域名` = '${domain}'\r\norder by time"
    }
   ]
  },
  {
   "title": "高峰时段每秒请求量与返回量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "rawSql": "SELECT `日期` as time, `最大请求量`,`最大返回量` from ${db}.${project} prewhere $__timeFilter(`日期`) and `域名` = '${domain}'\r\norder by time"
    }
   ]
  },
  {
   "title": "每日整体数据分析",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "每日总PV与总UV",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT `日期` as time, `总UV`,`总PV` from ${db}.${project} prewhere $__timeFilter(`日期`) and `域名` = '${domain}'\r\norder by time"
      }
     ]
    },
    {
     "title": "每日各请求状态分布",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT `日期` as time, `1xx`,`2xx`,`3xx`,`4xx`,`5xx` from ${db}.${project} prewhere $__timeFilter(`日期`) and `域名` = '${domain}'\r\norder by time"
      }
     ]
    },
    {
     "title": "每日请求成功率(status<400)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "SELECT `日期` as time, `请求成功率` from ${db}.${project} prewhere $__timeFilter(`日期`) and `域名` = '${domain}'\r\norder by time"
      }
     ]
    },
    {
     "title": "每日访问设备操作系统分布",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT `日期` as time, `Windows`,`Android`,`iOS`,`MAC`,`其它` from ${db}.${project} prewhere $__timeFilter(`日期`) and `域名` = '${domain}'\r\norder by time"
      }
     ]
    }
   ]
  },
  {
   "title": "每日整体异常请求数据排行榜",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "每日PV大于1000的URI请求,响应时间排行【格式: 响应时间:URI:请求次数】",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "rawSql": "SELECT `日期` as time, `慢path第一`,`慢path第二`,`慢path第三`,`慢path第四`,`慢path第五`,`慢path第六`,`慢path第七`,`慢path第八`,`慢path第九`,`慢path第十`  from ${db}.${project} prewhere $__timeFilter(`日期`) and `域名` = '${domain}'\r\norder by time desc"
      }
     ]
    },
    {
     "title": "每日各URI返回5XX次数排行【格式: 请求次数:URI】",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "rawSql": "SELECT `日期` as time, `5xx第一`,`5xx第二`,`5xx第三`,`5xx第四`,`5xx第五`,`5xx第六`,`5xx第七`,`5xx第八`,`5xx第九`,`5xx第十` from ${db}.${project} prewhere $__timeFilter(`日期`) and `域名` = '${domain}'\r\norder by time desc"
      }
     ]
    },
    {
     "title": "每日各URI返回4XX次数排行【格式: 请求次数:URI】",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "rawSql": "SELECT `日期` as time, `4xx第一`,`4xx第二`,`4xx第三`,`4xx第四`,`4xx第五`,`4xx第六`,`4xx第七`,`4xx第八`,`4xx第九`,`4xx第十` from ${db}.${project} prewhere $__timeFilter(`日期`) and `域名` = '${domain}'\r\norder by time desc"
      }
     ]
    }
   ]
  },
  {
   "title": "每日整体用户请求数据排行榜",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "每日各URI请求次数排行【格式: 请求次数:URI】",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "rawSql": "SELECT `日期` as time, `path第一`,`path第二`,`path第三`,`path第四`,`path第五`,`path第六`,`path第七`,`path第八`,`path第九`,`path第十` from ${db}.${project} prewhere $__timeFilter(`日期`) and `域名` = '${domain}'\r\norder by time desc"
      }
     ]
    },
    {
     "title": "每日各用户IP请求URI次数排行【格式: 请求次数:URI:用户IP】",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "rawSql": "SELECT `日期` as time, `IP-path第一`,`IP-path第二`,`IP-path第三`,`IP-path第四`,`IP-path第五`,`IP-path第六`,`IP-path第七`,`IP-path第八`,`IP-path第九`,`IP-path第十`  from ${db}.${project} prewhere $__timeFilter(`日期`) and `域名` = '${domain}'\r\norder by time desc"
      }
     ]
    },
    {
     "title": "每日各用户IP请求次数排行【格式: 请求次数:用户IP】",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "rawSql": "SELECT `日期` as time, `IP第一`,`IP第二`,`IP第三`,`IP第四`,`IP第五`,`IP第六`,`IP第七`,`IP第八`,`IP第九`,`IP第十` from ${db}.${project} prewhere $__timeFilter(`日期`) and `域名` = '${domain}'\r\norder by time desc"
      }
     ]
    }
   ]
  }
 ]
}